spring.application.name=demoProject

spring.datasource.username=akansha
spring.datasource.password=roy

spring.datasource.url=jdbc:h2:mem:testDB
spring.datasource.driverClassName=org.h2.Driver
spring.h2.console.enabled=true

#responsible to show queries thats doing stuff for us (CRUD) on its own BTS
spring.jpa.show-sql=true 

